document.addEventListener('DOMContentLoaded', function() {
    // Create a new div element
    var newDiv = document.createElement('div');

    // Set some HTML content for the div
    newDiv.innerHTML = '<p>This is HTML content generated by JavaScript!</p>';

    // Append the new div to the body
    document.body.appendChild(newDiv);
});